/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.*;
import static org.junit.Assert.*;
import java.util.*;
import org.sql2o.*;

public class EndangeredAnimalTest {
  @Rule
  public DatabaseRule database = new DatabaseRule();
	
	 @Test
  public void EndangeredAnimal_instantiatesCorrectly_true() 
	{
    EndangeredAnimal testAnimal = new EndangeredAnimal("chicken","healthy","young");
    assertEquals(true, testAnimal instanceof EndangeredAnimal);
  }
	
	@Test
  public void getName_animalInstantiatesWithName_Chicken() 
	{
    EndangeredAnimal testAnimal = new EndangeredAnimal("chicken","healthy","young");
    assertEquals("chicken", testAnimal.getName());
  }	
	
	@Test
  public void getHealth_animalInstantiatesWithHealth_healthy() 
	{
    EndangeredAnimal testAnimal = new EndangeredAnimal("chicken","healthy","young");
    assertEquals("healthy", testAnimal.getHealth());
  }	
	@Test
  public void getAge_animalInstantiatesWithAge_young() 
	{
    EndangeredAnimal testAnimal = new EndangeredAnimal("chicken","healthy","young");
    assertEquals("young", testAnimal.getAge());
  }
	
	@Test
  public void equals_returnsTrueIfNameAreSame_true() 
	{
    EndangeredAnimal testAnimal = new EndangeredAnimal("chicken","healthy","young");
    EndangeredAnimal anotherAnimal = new EndangeredAnimal("chicken","healthy","young");
    assertTrue(testAnimal.equals(anotherAnimal));
  }

	@Test
  public void save_insertsObjectIntoDatabase_EndangeredAnimal() 
	{
    EndangeredAnimal testAnimal = new EndangeredAnimal("chicken","healthy","young");
    testAnimal.save();
    assertEquals(true, EndangeredAnimal.allEndangered().get(0).equals(testAnimal));
  }
//	
	 @Test
  public void all_returnsAllInstancesOfPerson_true() 
	{
		EndangeredAnimal firstAnimal = new EndangeredAnimal("chicken","healthy","young");
    firstAnimal.save();
   	EndangeredAnimal secondAnimal = new EndangeredAnimal("elephant","healthy","young");
    secondAnimal.save();
    assertEquals(true, EndangeredAnimal.allEndangered().get(0).equals(firstAnimal));
    assertEquals(true, EndangeredAnimal.allEndangered().get(1).equals(secondAnimal));
  }

	@Test
	public void save_assignsIdToObject(){
    EndangeredAnimal testAnimal = new EndangeredAnimal("chicken","healthy","young");
		testAnimal.save();
		EndangeredAnimal savedAnimal = EndangeredAnimal.allEndangered().get(0);
		assertEquals(testAnimal.getId(),savedAnimal.getId());
	}
	@Test
  public void find_returnsEndangeredAnimalWithSameId_secondAnimal() {
   	EndangeredAnimal firstAnimal = new EndangeredAnimal("chicken","healthy","young");
    firstAnimal.save();
   	EndangeredAnimal secondAnimal = new EndangeredAnimal("elephant","healthy","young");
    secondAnimal.save();
    assertEquals(firstAnimal.find(secondAnimal.getId()), secondAnimal);
  }
}