/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.*;
import static org.junit.Assert.*;
import java.util.*;
import org.sql2o.*;

public class SightingTest 
{
	
  @Rule
  public DatabaseRule database = new DatabaseRule();
	
	@Test
	public void Sighting_instntiatesCorrectly_true(){
		Sighting testSighting = new Sighting("NE Quandrant", 1, "Ranger Dave");
		assertEquals(true, testSighting instanceof Sighting);
	}
	
	@Test
  public void Sighting_instantiatesWithGetters_String() {
		Sighting testSighting = new Sighting("NE Quandrant", 1, "Ranger Dave");
    assertEquals("NE Quandrant", testSighting.getLocation());
    assertEquals(1, testSighting.getAnimalId());
    assertEquals("Ranger Dave", testSighting.getRangerName());
  }
	
	@Test
  public void equals_returnsTrueIflocationAndAnimalIdAreSame_true() {
    Sighting testSighting = new Sighting("NE Quandrant", 1, "Ranger Dave");
    Sighting anotherSighting = new Sighting("NE Quandrant", 1, "Ranger Dave");
    assertTrue(testSighting.equals(anotherSighting));
  }
	
	@Test
  public void save_successfullyAddsSightingToDatabase_List() {
    Sighting testSighting = new Sighting("NE Quandrant", 1, "Ranger Dave");
    testSighting.save();
    assertTrue(Sighting.all().get(0).equals(testSighting));
  }
	
	@Test
  public void save_assignsIdToSighting() {
 		Sighting testSighting = new Sighting("NE Quandrant", 1, "Ranger Dave");
    testSighting.save();
    Sighting savedSighting = Sighting.all().get(0);
    assertEquals(savedSighting.getId(), testSighting.getId());
  }
	
	@Test
  public void all_returnsAllInstancesOfFireMonster_true() {
    Sighting firstSighting = new Sighting("NE Quandrant", 1, "Ranger Dave");
    firstSighting.save();
    Sighting  secondSighting = new Sighting("NW Quandrant", 2, "Ranger Steve");
    secondSighting.save();
    assertEquals(true, Sighting.all().get(0).equals(firstSighting));
    assertEquals(true, Sighting.all().get(1).equals(secondSighting));
  }
	
	
}